server:
  port: 12345

spring:
  application:
    name: exchange-example
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000